### ISSUE TITLE
ViT-B-16 img model convert to onnx failed

### ISSUE THREAD

**Issue by ALeeLee1986** [OFA-Sys/Chinese-CLIP#125]
Traceback (most recent call last):
  File "cn_clip/deploy/pytorch_to_onnx.py", line 139, in <module>
    torch.onnx.export(model,
  File "/home/lishixian/miniconda3/envs/tm2onnx/lib/python3.8/site-packages/torch/onnx/utils.py", line 506, in export
    _export(
  File "/home/lishixian/miniconda3/envs/tm2onnx/lib/python3.8/site-packages/torch/onnx/utils.py", line 1548, in _export
    graph, params_dict, torch_out = _model_to_graph(
  File "/home/lishixian/miniconda3/envs/tm2onnx/lib/python3.8/site-packages/torch/onnx/utils.py", line 1117, in _model_to_graph
    graph = _optimize_graph(
  File "/home/lishixian/miniconda3/envs/tm2onnx/lib/python3.8/site-packages/torch/onnx/utils.py", line 665, in _optimize_graph
    graph = _C._jit_pass_onnx(graph, operator_export_type)
  File "/home/lishixian/miniconda3/envs/tm2onnx/lib/python3.8/site-packages/torch/onnx/utils.py", line 1901, in _run_symbolic_function
    raise errors.UnsupportedOperatorError(
torch.onnx.errors.UnsupportedOperatorError: Exporting the operator 'aten::unflatten' to ONNX opset version 13 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub: https://github.com/pytorch/pytorch/issues.

**Comment by yangapku** [comment]
您好，建议您参考issue #112 ，看上去好像是同样的问题，您完全对应到我们deployment.md中所述的环境版本应该就可以了哈。
