### ISSUE TITLE
fairseq包的版本是多少？

### ISSUE THREAD

**Issue by AnitaSherry** [OFA-Sys/Chinese-CLIP#215]
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kemove/anaconda3/envs/nlp/lib/python3.11/site-packages/modelscope/pipelines/builder.py", line 147, in pipeline
    pipeline_props = {'type': pipeline_name}
   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kemove/anaconda3/envs/nlp/lib/python3.11/site-packages/modelscope/pipelines/builder.py", line 59, in build_pipeline
    Args:
         
  File "/home/kemove/anaconda3/envs/nlp/lib/python3.11/site-packages/modelscope/utils/registry.py", line 184, in build_from_cfg
    LazyImportModule.import_module(sig)
  File "/home/kemove/anaconda3/envs/nlp/lib/python3.11/site-packages/modelscope/utils/import_utils.py", line 459, in import_module
    requirements = LazyImportModule.AST_INDEX[REQUIREMENT_KEY][
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kemove/anaconda3/envs/nlp/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/kemove/anaconda3/envs/nlp/lib/python3.11/site-packages/modelscope/pipelines/multi_modal/multi_modal_embedding_pipeline.py", line 9, in <module>
    from modelscope.preprocessors.multi_modal import CLIPPreprocessor, Preprocessor
  File "/home/kemove/anaconda3/envs/nlp/lib/python3.11/site-packages/modelscope/preprocessors/multi_modal.py", line 29, in <module>
    from .ofa import *  # noqa
    ^^^^^^^^^^^^^^^^^^
  File "/home/kemove/anaconda3/envs/nlp/lib/python3.11/site-packages/modelscope/preprocessors/ofa/__init__.py", line 2, in <module>
    from .asr import OfaASRPreprocessor
  File "/home/kemove/anaconda3/envs/nlp/lib/python3.11/site-packages/modelscope/preprocessors/ofa/asr.py", line 13, in <module>
    from fairseq.data.audio.speech_to_text_dataset import S2TDataConfig
  File "/home/kemove/anaconda3/envs/nlp/lib/python3.11/site-packages/fairseq/data/audio/speech_to_text_dataset.py", line 19, in <module>
    from fairseq.data import ConcatDataset, Dictionary, FairseqDataset, ResamplingDataset
  File "/home/kemove/anaconda3/envs/nlp/lib/python3.11/site-packages/fairseq/__init__.py", line 20, in <module>
    from fairseq.distributed import utils as distributed_utils
  File "/home/kemove/anaconda3/envs/nlp/lib/python3.11/site-packages/fairseq/distributed/__init__.py", line 7, in <module>
    from .fully_sharded_data_parallel import (
  File "/home/kemove/anaconda3/envs/nlp/lib/python3.11/site-packages/fairseq/distributed/fully_sharded_data_parallel.py", line 10, in <module>
    from fairseq.dataclass.configs import DistributedTrainingConfig
  File "/home/kemove/anaconda3/envs/nlp/lib/python3.11/site-packages/fairseq/dataclass/configs.py", line 1104, in <module>
    @dataclass
     ^^^^^^^^^
  File "/home/kemove/anaconda3/envs/nlp/lib/python3.11/dataclasses.py", line 1230, in dataclass
    return wrap(cls)
           ^^^^^^^^^
  File "/home/kemove/anaconda3/envs/nlp/lib/python3.11/dataclasses.py", line 1220, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kemove/anaconda3/envs/nlp/lib/python3.11/dataclasses.py", line 958, in _process_class
    cls_fields.append(_get_field(cls, name, type, kw_only))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kemove/anaconda3/envs/nlp/lib/python3.11/dataclasses.py", line 815, in _get_field
    raise ValueError(f'mutable default {type(f.default)} for field '
ValueError: mutable default <class 'fairseq.dataclass.configs.CommonConfig'> for field common is not allowed: use default_factory`

**Comment by yangapku** [comment]
您好，确认下您是需要知识蒸馏的功能吗？看上去这个是modelscope的依赖之一，如果不使用此功能的话，modelscope是不需要安装的，也不会安装fairseq哈

**Comment by AnitaSherry** [comment]
> 您好，确认下您是需要知识补充的功能吗？了解这是 modelscope 的依赖，如果不使用此功能的话，modelscope 是不需要安装的，也不会安装 fairseq 哈

我完全按照，[CLIP模型-中文-通用领域-large-336分辨率](https://modelscope.cn/models/damo/multi-modal_clip-vit-large-patch14_336_zh/summary)，进行快速使用，报错ValueError: mutable default <class 'fairseq.dataclass.configs.CommonConfig'> for field common is not allowed: use default_factory。更换了fairseq所有的版本都无效。现在问题已经解决了，不使用modelscope，直接使用你们的代码就跑通了。
