### ISSUE TITLE
windows 单机单卡 脚本运行

### ISSUE THREAD

**Issue by WenZiCyan** [OFA-Sys/Chinese-CLIP#217]
`$ bash run_scripts/muge_finetune_vit-b-16_rbt-base.sh
NOTE: Redirects are currently not supported in Windows or MacOs.
Traceback (most recent call last):
  File "D:\Chinese-CLIP\cn_clip\training\main.py", line 17, in <module>
    from cn_clip.clip.model import convert_weights, convert_state_dict, resize_pos_embed, CLIP
ImportError: cannot import name 'convert_state_dict' from 'cn_clip.clip.model' (C:\Users\4091\.conda\envs\clip39\lib\site-packages\cn_clip\clip\model.py)
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 16028) of binary: C:\Users\4091\.conda\envs\clip39\python.exe
Traceback (most recent call last):
  File "C:\Users\4091\.conda\envs\clip39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\4091\.conda\envs\clip39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\4091\.conda\envs\clip39\Scripts\torchrun.exe\__main__.py", line 7, in <module>
  File "C:\Users\4091\.conda\envs\clip39\lib\site-packages\torch\distributed\elastic\multiprocessing\errors\__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "C:\Users\4091\.conda\envs\clip39\lib\site-packages\torch\distributed\run.py", line 794, in main
    run(args)
  File "C:\Users\4091\.conda\envs\clip39\lib\site-packages\torch\distributed\run.py", line 785, in run
    elastic_launch(
  File "C:\Users\4091\.conda\envs\clip39\lib\site-packages\torch\distributed\launcher\api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "C:\Users\4091\.conda\envs\clip39\lib\site-packages\torch\distributed\launcher\api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
cn_clip/training/main.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-10-12_19:23:42
  host      : DESKTOP-HSGCL12
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 16028)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
`
你好，这是我的报错

**Comment by WenZiCyan** [comment]
`GPUS_PER_NODE=1
# Number of GPU workers, for single-worker training, please set to 1
WORKER_CNT=1
# The ip address of the rank-0 worker, for single-worker training, please set to
export MASTER_ADDR=localhost
# The port for communication
export MASTER_PORT=8514
# The rank of this worker, should be in {0, ..., WORKER_CNT-1}, for single-worker training, please set to 0
export RANK=0

export PYTHONPATH=${PYTHONPATH}:`pwd`/cn_clip/

# data options
train_data=D:/Chinese-CLIP/data/datasets/ChinaWare/lmdb/train
val_data=D:/Chinese-CLIP/data/datasets/ChinaWare/lmdb/valid # if val_data is not specified, the validation will be automatically disabled

# restore options
resume=D:/Chinese-CLIP/data/pretrained_weights/clip_cn_vit-b-16.pt # or specify your customed ckpt path to resume
reset_data_offset="--reset-data-offset"
reset_optimizer="--reset-optimizer"
# reset_optimizer=""

# output options
output_base_dir=D:/Chinese-CLIP/data/experiments/
name=muge_finetune_vit-b-16_roberta-base_bs128_8gpu
save_step_frequency=999999 # disable it
save_epoch_frequency=1
log_interval=1
report_training_batch_acc="--report-training-batch-acc"
# report_training_batch_acc=""

# training hyper-params
context_length=52
warmup=100
batch_size=32
valid_batch_size=32
accum_freq=1
lr=5e-5
wd=0.001
max_epochs=3 # or you can alternatively specify --max-steps
valid_step_interval=150
valid_epoch_interval=1
vision_model=ViT-B-16
text_model=RoBERTa-wwm-ext-base-chinese
use_augment="--use-augment"
# use_augment=""

torchrun --nproc_per_node=${GPUS_PER_NODE} --nnodes=${WORKER_CNT} --node_rank=${RANK} \
          --master_addr=${MASTER_ADDR} --master_port=${MASTER_PORT} cn_clip/training/main.py \
          --train-data=${train_data} \
          --val-data=${val_data} \
          --resume=${resume} \
          ${reset_data_offset} \
          ${reset_optimizer} \
          --logs=${output_base_dir} \
          --name=${name} \
          --save-step-frequency=${save_step_frequency} \
          --save-epoch-frequency=${save_epoch_frequency} \
          --log-interval=${log_interval} \
          ${report_training_batch_acc} \
          --context-length=${context_length} \
          --warmup=${warmup} \
          --batch-size=${batch_size} \
          --valid-batch-size=${valid_batch_size} \
          --valid-step-interval=${valid_step_interval} \
          --valid-epoch-interval=${valid_epoch_interval} \
          --accum-freq=${accum_freq} \
          --lr=${lr} \
          --wd=${wd} \
          --max-epochs=${max_epochs} \
          --vision-model=${vision_model} \
          ${use_augment} \
          --text-model=${text_model}`

这是.sh文件

**Comment by WenZiCyan** [comment]
![微信截图_20231012192207](https://github.com/OFA-Sys/Chinese-CLIP/assets/23072653/09c2bcc6-38e0-425f-a425-5340b484d066)
你好，这是我的报错

**Comment by WenZiCyan** [comment]
![微信截图_20231012192904](https://github.com/OFA-Sys/Chinese-CLIP/assets/23072653/0f65ee49-20dc-454a-a4e4-998097ed13e6)
![微信截图_20231012192926](https://github.com/OFA-Sys/Chinese-CLIP/assets/23072653/6adfc5c3-860c-4df9-b0ac-3915c4ab59fc)

**Comment by WenZiCyan** [comment]
torch-2.0.0+cu118-cp39
torchaudio-2.0.0+cu118-cp39
torchvision-0.15.0+cu118-cp39

**Comment by WanEven** [comment]
我也遇到了同样的问题，能请问下你怎么解决的吗

**Comment by WenZiCyan** [comment]
> 我也遇到了同样的问题，能请问下你怎么解决的吗

pytorch 版本没装对

**Comment by ctgushiwei** [comment]
单机单卡 torch1.7.3 cu116自己实验是可以的
