### ISSUE TITLE
转onnx出错

### ISSUE THREAD

**Issue by bendanzzc** [OFA-Sys/Chinese-CLIP#25]
hello，感谢开源cnclip，我用自己的数据 finetune了 cnclip 并想把vision模块转成onnx，转完之后 用onnxruntime运行包如下错，请问是什么情况呀
2022-12-06 20:54:43.837539176 [E:onnxruntime:, sequential_executor.cc:368 Execute] Non-zero status code returned while running Reshape node. Name:'Reshape_54' Status Message: /onnxruntime_src/onnxruntime/core/providers/cpu/tensor/reshape_helper.h:40 onnxruntime::ReshapeHelper::ReshapeHelper(const onnxruntime::TensorShape&, onnxruntime::TensorShapeVector&, bool) gsl::narrow_cast<int64_t>(input_shape.Size()) == size was false. The input tensor cannot be reshaped to the requested shape. Input shape:{197,1,768}, requested shape:{197,2364,64}

Traceback (most recent call last):
  File "test.py", line 18, in <module>
    (text_feature) = sessison.run(output_names, {'image': image})
  File "/home/jovyan/.local/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 200, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running Reshape node. Name:'Reshape_54' Status Message: /onnxruntime_src/onnxruntime/core/providers/cpu/tensor/reshape_helper.h:40 onnxruntime::ReshapeHelper::ReshapeHelper(const onnxruntime::TensorShape&, onnxruntime::TensorShapeVector&, bool) gsl::narrow_cast<int64_t>(input_shape.Size()) == size was false. The input tensor cannot be reshaped to the requested shape. Input shape:{197,1,768}, requested shape:{197,2364,64}

**Comment by yangapku** [comment]
您好，目前我们确实还没有尝试过给模型转ONNX，我们排查下这个问题。

**Comment by bendanzzc** [comment]
解决了，应该是nn.MultiheadAttention的问题，不同版本的实现不一样，导致onnx转换出错，1.13.0的torch版本没问题

**Comment by yangapku** [comment]
您好，同步下最新消息~ 我们最新的Chinese-CLIP代码，目前已经支持转ONNX和TensorRT了哈，相关文档详见[deployment.md](https://github.com/OFA-Sys/Chinese-CLIP/blob/master/deployment.md)
