### ISSUE TITLE
ImportError: cannot import name 'convert_state_dict' from 'cn_clip.clip.model'

### ISSUE THREAD

**Issue by IF-chan** [OFA-Sys/Chinese-CLIP#260]
在跨模态检索模型finetune运行脚本时发生的错误

Traceback (most recent call last):                                                                                                                                                             File "/mnt/e/Chinese-CLIP/cn_clip/training/main.py", line 17, in <module>                                                                                                                      from cn_clip.clip.model import convert_weights, convert_state_dict, resize_pos_embed, CLIP                                                                                               ImportError: cannot import name 'convert_state_dict' from 'cn_clip.clip.model' (/home/abc/.local/lib/python3.10/site-packages/cn_clip/clip/model.py)                                         [2024-02-28 00:26:24,741] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 537) of binary: /usr/bin/python3                                   Traceback (most recent call last):                                                                                                                                                             File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main                                                                                                                          return _run_code(code, main_globals, None,                                                                                                                                                 File "/usr/lib/python3.10/runpy.py", line 86, in _run_code                                                                                                                                     exec(code, run_globals)                                                                                                                                                                    File "/home/abc/.local/lib/python3.10/site-packages/torch/distributed/launch.py", line 198, in <module>                                                                                        main()                                                                                                                                                                                     File "/home/abc/.local/lib/python3.10/site-packages/torch/distributed/launch.py", line 194, in main                                                                                            launch(args)                                                                                                                                                                               File "/home/abc/.local/lib/python3.10/site-packages/torch/distributed/launch.py", line 179, in launch                                                                                          run(args)                                                                                                                                                                                  File "/home/abc/.local/lib/python3.10/site-packages/torch/distributed/run.py", line 803, in run                                                                                                elastic_launch(                                                                                                                                                                            File "/home/abc/.local/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 135, in __call__                                                                                  return launch_agent(self._config, self._entrypoint, list(args))                                                                                                                            File "/home/abc/.local/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 268, in launch_agent                                                                              raise ChildFailedError(                                                                                                                                                                  torch.distributed.elastic.multiprocessing.errors.ChildFailedError:                                                                                                                           ============================================================                                                                                                                                 /mnt/e/Chinese-CLIP/cn_clip/training/main.py FAILED                                                                                                                                          ------------------------------------------------------------                                                                                                                                 Failures:                                                                                                                                                                                      <NO_OTHER_FAILURES>                                                                                                                                                                        ------------------------------------------------------------                                                                                                                                 Root Cause (first observed failure):                                                                                                                                                         [0]:                                                                                                                                                                                           time      : 2024-02-28_00:26:24                                                                                                                                                              host      : LAPTOP-RH435GU1.                                                                                                                                                                 rank      : 0 (local_rank: 0)                                                                                                                                                                exitcode  : 1 (pid: 537)                                                                                                                                                                     error_file: <N/A>                                                                                                                                                                            traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html                                                                                                   ============================================================

**Comment by Daydaylight** [comment]
请问这一问题是什么原因导致的？可以告诉我你是如何解决的吗？

**Comment by zzy133** [comment]
原因：如果是通过pycharm编译器运行项目，由于cn_clip是本地文件,引入包的时候要将其作为sources root
解决方式：将cn_clip的上级目录，一般是Chinese-CLIP-master，在这个文件目录上右键-Mark Directory as -Sources Root
