### ISSUE TITLE
fine tune报线程错误 求指导

### ISSUE THREAD

**Issue by lll1024** [OFA-Sys/Chinese-CLIP#318]
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/liujiawei/anaconda3/envs/game0/lib/python3.8/threading.py", line 932, in _bootstrap_inner

**Comment by sun254667307** [comment]
dataloader设置num_workers=0

**Comment by lll1024** [comment]
num_workers=0 # 训练集pytorch dataloader的进程数，设置为>0，以减小训练时读取数据的时间开销
valid_num_workers=0 # 验证集pytorch dataloader的进程数，设置为>0，以减小验证时读取数据的时间开销
我已经把这两个参数设为0了，但还是报这个错误：
Exception in thread Thread-1:
Traceback (most recent call last):

**Comment by lll1024** [comment]
File "/home/liujiawei/anaconda3/envs/game0/lib/python3.8/threading.py", line 932, in _bootstrap_inner
不过这一行没有出现了
