### ISSUE TITLE
使用下列代码，如何加载自己训练的 'ViT-L-14'模型指定路径的.pt文件。（比如加载Epoch为2的./data/model/epoch2.pt模型）

### ISSUE THREAD

**Issue by laitianan** [OFA-Sys/Chinese-CLIP#345]
import torch 
from PIL import Image

import cn_clip.clip as clip
from cn_clip.clip import load_from_name, available_models
print("Available models:", available_models())  
# Available models: ['ViT-B-16', 'ViT-L-14', 'ViT-L-14-336', 'ViT-H-14', 'RN50']

device = "cuda" if torch.cuda.is_available() else "cpu"
model, preprocess = load_from_name("ViT-B-16", device=device, download_root='./')
model.eval()
image = preprocess(Image.open("examples/pokemon.jpeg")).unsqueeze(0).to(device)
text = clip.tokenize(["杰尼龟", "妙蛙种子", "小火龙", "皮卡丘"]).to(device)

with torch.no_grad():
    image_features = model.encode_image(image)
    text_features = model.encode_text(text)
    # 对特征进行归一化，请使用归一化后的图文特征用于下游任务
    image_features /= image_features.norm(dim=-1, keepdim=True) 
    text_features /= text_features.norm(dim=-1, keepdim=True)    

    logits_per_image, logits_per_text = model.get_similarity(image, text)
    probs = logits_per_image.softmax(dim=-1).cpu().numpy()

print("Label probs:", probs)  # [[1.268734e-03 5.436878e-02 6.795761e-04 9.436829e-01]]

**Comment by ChesonHuang** [comment]
假设你的pt文件路径是，your_path= ‘xxx.pt’
```python
your_path= ‘xxx.pt’
model, preprocess = load_from_name(your_path, vision_model_name='ViT-L-14-336', text_model_name='RoBERTa-wwm-ext-base-chinese')
# 上面的vision_model_name和text_model_name要具体决定，因为你是ViT-L-14，就用上面的就行
```

**Comment by ZYF-fmg** [comment]
you can try the code next.
`model, preprocess = clip.from_pretrained("model_path")`

**Comment by xiaoAugenstern** [comment]
> you can try the code next. `model, preprocess = clip.from_pretrained("model_path")`

    model, preprocess = clip.from_pretrained(model_path)
AttributeError: module 'cn_clip.clip' has no attribute 'from_pretrained'

**Comment by ZYF-fmg** [comment]
> > you can try the code next. `model, preprocess = clip.from_pretrained("model_path")`
> 
> ```
> model, preprocess = clip.from_pretrained(model_path)
> ```
> 
> AttributeError: module 'cn_clip.clip' has no attribute 'from_pretrained'

![image](https://github.com/user-attachments/assets/77caed94-d027-44b0-b250-a148653fbcfd)
try clip.load() function

**Comment by GameHab** [comment]
提前设置好你模型文件的位置，然后用下面的代码：
```python
clip_path  = ''/data/model/epoch2.pt' 
device = "cuda" if torch.cuda.is_available() else "cpu"
model, preprocess = load_from_name(clip_path, device=device, vision_model_name="ViT-B-16", text_model_name="RoBERTa-wwm-ext-base-chinese", input_resolution=224)
```

**Comment by xiaoAugenstern** [comment]
您好，您的工作做的非常好，
请问我用"ViT-B-16"在我自己的数据集上面微调了一个：
`model_path = 'experiments/HandWritten_finetune_vit-b-16_roberta-base_bs128_8gpu/checkpoints/epoch_latest.pt'`
    
如何用这个微调好的模型，做图片分类，例如您[api的例子](https://github.com/OFA-Sys/Chinese-CLIP/?tab=readme-ov-file#api%E5%BF%AB%E9%80%9F%E4%B8%8A%E6%89%8B)

```
   model, preprocess = load_from_name("ViT-B-16", device=device, download_root='./')
    checkpoint = torch.load(model_path, map_location=device)
    start_epoch = checkpoint["epoch"]
    sd = checkpoint["state_dict"]
    if next(iter(sd.items()))[0].startswith('module'):
        sd = {k[len('module.'):]: v for k, v in sd.items() if "bert.pooler" not in k}
    model.load_state_dict(sd)
    print(
        f"=> loaded checkpoint '{model}' (epoch {checkpoint['epoch']} @ {checkpoint['step']} steps)"
    )
    # 准备数据
    image = preprocess(Image.open(image_path)).unsqueeze(0).to(device)
    print(f"Image shape after preprocessing: {image.shape}")  # 检查图像形状
    text = clip.tokenize(candidate_labels).to(device)
    # 推理
    with torch.no_grad():
        image_features = model.encode_image(image)
        text_features = model.encode_text(text)
     
        # 对特征进行归一化
        image_features /= image_features.norm(dim=-1, keepdim=True)
        text_features /= text_features.norm(dim=-1, keepdim=True)

        # 计算相似度
        logits_per_image, logits_per_text = model.get_similarity(image_features, text_features)
        probs = logits_per_image.softmax(dim=-1).cpu().numpy()
    return probs

```

我好像也成功导入了模型，
![image](https://github.com/user-attachments/assets/a1142efa-6d2b-4074-9d7c-3191e4895fa5)

但是在做图片encode的时候，会报错：

```
Image shape after preprocessing: torch.Size([1, 3, 224, 224])
torch.Size([1, 512])
Traceback (most recent call last):
  File "/home/xiaoman/project/clip/datapath/test.py", line 184, in <module>
    probs = predict_image_label(image_path, candidate_labels,model_path)
  File "/home/xiaoman/project/clip/datapath/test.py", line 118, in predict_image_label
    logits_per_image, logits_per_text = model.get_similarity(image_features, text_features)
  File "/home/xiaoman/anaconda3/envs/pytorch/lib/python3.8/site-packages/cn_clip/clip/model.py", line 406, in get_similarity
    image_features = self.encode_image(image)
  File "/home/xiaoman/anaconda3/envs/pytorch/lib/python3.8/site-packages/cn_clip/clip/model.py", line 382, in encode_image
    return self.visual(image.type(self.dtype), mask_ratio)
  File "/home/xiaoman/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/xiaoman/anaconda3/envs/pytorch/lib/python3.8/site-packages/cn_clip/clip/model.py", line 260, in forward
    x = self.conv1(x)  # shape = [*, width, grid, grid]
  File "/home/xiaoman/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/xiaoman/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 457, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/xiaoman/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 453, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Expected 3D (unbatched) or 4D (batched) input to conv2d, but got input of size: [1, 512]
```

**Comment by xiaoAugenstern** [comment]
> 提前设置好你模型文件的位置，然后用下面的代码：
> 
> ```python
> clip_path  = ''/data/model/epoch2.pt' 
> device = "cuda" if torch.cuda.is_available() else "cpu"
> model, preprocess = load_from_name(clip_path, device=device, vision_model_name="ViT-B-16", text_model_name="RoBERTa-wwm-ext-base-chinese", input_resolution=224)
> ```

    model, preprocess = load_from_name(clip_path, device=device, vision_model_name="ViT-B-16",
TypeError: load_from_name() got an unexpected keyword argument 'vision_model_name'
好像不太行

**Comment by GameHab** [comment]
> > 提前设置好你模型文件的位置，然后用下面的代码：
> > ```python
> > clip_path  = ''/data/model/epoch2.pt' 
> > device = "cuda" if torch.cuda.is_available() else "cpu"
> > model, preprocess = load_from_name(clip_path, device=device, vision_model_name="ViT-B-16", text_model_name="RoBERTa-wwm-ext-base-chinese", input_resolution=224)
> > ```
> 
> ```
> model, preprocess = load_from_name(clip_path, device=device, vision_model_name="ViT-B-16",
> ```
> 
> TypeError: load_from_name() got an unexpected keyword argument 'vision_model_name' 好像不太行

没有这个vision_model_name?你导入cn_clip了吗
```python
import cn_clip.clip as clip
from cn_clip.clip import load_from_name, available_models
```

**Comment by Charimanhua** [comment]
请问你们有遇到
ModuleNotFoundError: No module named 'flash_attn.flash_attention'
报错么？请问你们是如何解决的？谢谢！

**Comment by jeborit** [comment]
> 请问你们有遇到 ModuleNotFoundError: No module named 'flash_attn.flash_attention' 报错么？请问你们是如何解决的？谢谢！

pip install ninja
pip install flash_attn == 0.2.8
