### ISSUE TITLE
AttributeError: 'ChineseCLIPConfig' object has no attribute 'hidden_size'

### ISSUE THREAD

**Issue by Manjiz** [OFA-Sys/Chinese-CLIP#347]
不确定是否应该提 issue 到这里，在 transformers 里的代码执行的时候抛了这个错：

```
AttributeError: 'ChineseCLIPConfig' object has no attribute 'hidden_size'
```

不知道是不是因为模型不支持 sentence_transformers。

完整错误如下：

```
Traceback (most recent call last):
  File "/usr/local/python3/bin/eland_import_hub_model", line 8, in <module>
    sys.exit(main())
  File "/usr/local/python3/lib/python3.8/site-packages/eland/cli/eland_import_hub_model.py", line 279, in main
    tm = TransformerModel(
  File "/usr/local/python3/lib/python3.8/site-packages/eland/ml/pytorch/transformers.py", line 665, in __init__
    self._traceable_model = self._create_traceable_model()
  File "/usr/local/python3/lib/python3.8/site-packages/eland/ml/pytorch/transformers.py", line 1000, in _create_traceable_model
    model = _SentenceTransformerWrapperModule.from_pretrained(
  File "/usr/local/python3/lib/python3.8/site-packages/eland/ml/pytorch/transformers.py", line 325, in from_pretrained
    return _SentenceTransformerWrapper(model, output_key)
  File "/usr/local/python3/lib/python3.8/site-packages/eland/ml/pytorch/transformers.py", line 352, in __init__
    super().__init__(model=model, output_key=output_key)
  File "/usr/local/python3/lib/python3.8/site-packages/eland/ml/pytorch/transformers.py", line 298, in __init__
    self._st_model = SentenceTransformer(model.config.name_or_path)
  File "/usr/local/python3/lib/python3.8/site-packages/sentence_transformers/SentenceTransformer.py", line 202, in __init__
    modules = self._load_auto_model(
  File "/usr/local/python3/lib/python3.8/site-packages/sentence_transformers/SentenceTransformer.py", line 973, in _load_auto_model
    pooling_model = Pooling(transformer_model.get_word_embedding_dimension(), "mean")
  File "/usr/local/python3/lib/python3.8/site-packages/sentence_transformers/models/Transformer.py", line 114, in get_word_embedding_dimension
    return self.auto_model.config.hidden_size
  File "/usr/local/python3/lib/python3.8/site-packages/transformers/configuration_utils.py", line 262, in __getattribute__
    return super().__getattribute__(key)
AttributeError: 'ChineseCLIPConfig' object has no attribute 'hidden_size'
```

**Comment by bk112** [comment]
问题同在，请问你解决了吗
